name: Build GUI for Windows with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v4
      with:
        name: kbvs
        path: dist/windows
